error: Dockerfile problematic. Saved for Posterity
Context:

The directory structure of this project is:

/isp-monitor (git)
    requirements.txt
    .envrc
    some .md files
    /isp_monitor
        api/
        cli/
        isps/
        isp_monitor.py

The current Dockerfile is here:
FROM python:3.8

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./ /code/app

CMD ["uvicorn", "isp_monitor.api.main:app", "--host", "0.0.0.0", "--port", "80"]

Problem:

WORKDIR /code sets the workdir in the docker container to /code

COPY ./requirements.txt /code/requirements.txt works perfectly

RUN command works fine as well.

COPY ./ /code/app is where the problem begins

That copies the content of isp-monitor/ inside dockercontainer/code/app

And since the WORKDIR is set to /code

CMD ["uvicorn...."] is run inside /code

which results in python looking for isp_monitor module inside

/code and not inside /code/app where isp_monitor/ exists.

Learnings:
app/ is redundant. It will be removed.
All contents inside isp-monitor including the .envrc is being copied
inside the docker image. Not good. Secrets need to be kept secret.
Need a way to handle secrets. Hmmm, -e option for docker?